# YAML file for Java project

# Specify the runtime environment
runtime: java

# Define the dependencies for your project
dependencies:
  - mysql:mysql-connector-java:8.0.26

# Define the build instructions for your project
build:
  # Specify the main class for your project
  main: com.anahuac.calidad.unitariasCRUD.dao.DAOAlumnoMySQL
  
  # Specify the files that need to be included in the build
  files:
    - com
    - iniDB.xml
    
  script:
    - javac com/anahuac/calidad/unitariasCRUD/dao/*.java com/anahuac/calidad/unitariasCRUD/entidades/*.java
    - jar -cvfm your-jar-file-name.jar manifest.txt com
    
  # Specify the command to run your project
  - run:
          name: Unit Test
          command: mvn test -Dtest="ServicioAlumnoTest"
      - run:
          name: Integration Test
          command: mvn test -Dtest="DAOAlumnoTest"
