version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11-browsers-legacy
        environment:
          DB_ROOT_USER: root
          DB_URL: jdbc:mysql://localhost:3307/calidad
          DB_DRIVER: com.mysql.cj.jdbc.Driver
          DB_PASS: ""
      - image: circleci/mysql:latest-ram
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install client
          command: | 
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt-get update
            sudo apt-get install default-mysql-client --fix-missing
      - run:
          name: Stop existing Xvfb server
          command: |
            sudo pkill Xvfb || true
            sudo rm -f /tmp/.X99-lock
      - run:
          name: Start Xvfb
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true
      - run:
          name: Unit Test
          command: mvn test -Dtest="ServicioAlumnoTest"
      - run:
          name: Test
          command: mvn test

workflows:
  sample:
    jobs:
      - build-and-test
